/*
  GOAL: Create a relational view that combines information about revenue by type of subscription plan, allowing detailed analyses of the revenue generated by each category of plan.
  BUSINESS QUESTION: What is the total revenue generated by each subscription plan type?
*/

USE hbo_db;
GO

DROP VIEW IF EXISTS dbo.vw_revenue_by_plan;
GO

CREATE VIEW dbo.vw_revenue_by_plan
AS
    SELECT
        p.name AS [plan_type],
        SUM(p.price) AS [total_revenue]
    FROM dbo.plans AS p JOIN dbo.subscriptions AS s ON
    p.id = s.plan_id
    WHERE s.status = 'active'
    GROUP BY p.name
GO